# Generated by Django 3.0 on 2020-07-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200709_0441'),
        ('cart', '0008_auto_20200628_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='products.Estoque'),
        ),
    ]
