# Generated by Django 3.0 on 2020-07-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200712_0253'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0010_auto_20200711_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='products.Estoque'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
