# Generated by Django 3.0 on 2020-07-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200711_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage', to='products.Produto'),
        ),
    ]
