# Generated by Django 3.0 on 2020-07-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200715_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='products.Produto'),
        ),
    ]
